export default {
  MENU_PRINCIPAL: "Menu",
  CATEGORIAS: "Categorias",
  TAB_CATEGORIAS_ARAÑAS: "Arañas",
  TAB_CATEGORIAS_ESCORPIONES: "Escorpiones",
  CATEGORIA_ARACNIDO: "Araña1",
  CATEGORIA_ARAC: "Araña2",
  CATEGORIA_ARAÑA:"Araña3",
  CATEGORIA_ARAÑAR:"Araña4",
  CATEGORIA_ARAÑAS:"Araña5",
  CATEGORIA_ARAÑAP:"Araña6",
  CATEGORIA_ARAÑAD:"Araña7",
  CATEGORIA_ESCORPION: "escorpion1",
  CATEGORIA_ESCORPION1: "escorpion2",
  CATEGORIA_ESCORPION2: "escorpion3",
  AVIST_CATEGORIA: "AvistCategoria",
};

